[package]
name = "url-oxidizer"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rocket = "0.5.0-rc.3"
clap = { version = "4.4", features = ["derive"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
